SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS C
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH
    ON C.CAR_ID = CH.CAR_ID
WHERE C.CAR_TYPE = '세단' 
    AND DATE_FORMAT(CH.START_DATE, '%Y-%m-%d') LIKE '%-10-%'
ORDER BY C.CAR_ID DESC
;