SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME 
FROM FOOD_PRODUCT 
WHERE (CATEGORY, PRICE) IN ( -- 필터링을 한 임시 테이블을 만들고 메인 테이블과 일치하는 행을 찾음
    SELECT CATEGORY, MAX(PRICE) 
    FROM FOOD_PRODUCT 
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유') 
    GROUP BY CATEGORY 
    )
ORDER BY PRICE DESC;