SELECT
    ROUTE,
    CONCAT(
        TRIM(TRAILING '.' FROM TRIM(TRAILING '0' FROM CAST(ROUND(SUM(D_BETWEEN_DIST), 1) AS CHAR))),
        'km'
    ) AS TOTAL_DISTANCE,
    -- TRIM(TRAILING '0' FROM '123.4500')
    
    CONCAT(
        TRIM(TRAILING '.' FROM TRIM(TRAILING '0' FROM CAST(ROUND(AVG(D_BETWEEN_DIST), 2) AS CHAR))),
        'km'
    ) AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY SUM(D_BETWEEN_DIST) DESC;
