SELECT DISTINCT
    UU.USER_ID, 
    UU.NICKNAME,  
    CONCAT(UU.CITY, ' ', UU.STREET_ADDRESS1, ' ', UU.STREET_ADDRESS2) 
    AS 전체주소,
    CONCAT(LEFT(UU.TLNO, 3), '-', SUBSTRING(UU.TLNO, 4, 4), '-', RIGHT(UU.TLNO, 4))
    AS 전화번호
FROM USED_GOODS_BOARD AS UB
    LEFT JOIN USED_GOODS_USER AS UU
    ON UB.WRITER_ID = UU.USER_ID
WHERE UU.USER_ID IN (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(*) >= 3
)
ORDER BY UU.USER_ID DESC
;