SELECT 
    HISTORY_ID,
    CAR_ID,
    DATE_FORMAT(START_DATE, '%Y-%m-%d') AS START_DATE,
    DATE_FORMAT(END_DATE, '%Y-%m-%d') AS END_DATE,
    CASE 
        WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 30 THEN '장기 대여' -- DATEDIFF는 시작일 미포함. DATEDIFF + 1 처리 필요함. 코딩 테스트에서 단골 함정임
        WHEN DATEDIFF(END_DATE, START_DATE)+1 < 30 THEN '단기 대여'
    END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, '%Y-%m-%d') LIKE '2022-09-%'
ORDER BY HISTORY_ID DESC
;