SELECT 
    q.quarter AS QUARTER,
    COUNT(*) AS ECOLI_COUNT
FROM (
    SELECT CONCAT(QUARTER(DIFFERENTIATION_DATE), 'Q') AS quarter
    FROM ECOLI_DATA
) q
GROUP BY q.quarter
ORDER BY CAST(LEFT(q.quarter, 1) AS UNSIGNED) ASC
;
