SELECT C.ID, C.GENOTYPE, P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA C
JOIN ECOLI_DATA P
    ON C.PARENT_ID = P.ID -- SELF JOIN을 통해 부모 형질-자식 형질 같은 것 끼리 
WHERE (C.GENOTYPE & P.GENOTYPE) = P.GENOTYPE -- 비트 연산으로 부모 형질이 모두 자식 형질에 포함되는지 판단
ORDER BY C.ID ASC
;