SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY,
    SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
FROM BOOK B
    LEFT JOIN AUTHOR A
    ON B.AUTHOR_ID = A.AUTHOR_ID
    LEFT JOIN BOOK_SALES BS
    ON B.BOOK_ID = BS.BOOK_ID
WHERE BS.SALES_DATE LIKE '2022-01-%'
GROUP BY B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC
;