SELECT CONCAT(
    '/home/grep/src/', 
    UF.BOARD_ID, '/',
    UF.FILE_ID, 
    UF.FILE_NAME, 
    UF.FILE_EXT
    ) AS FILE_PATH
FROM USED_GOODS_BOARD AS UB
    LEFT JOIN USED_GOODS_FILE AS UF
    ON UB.BOARD_ID = UF.BOARD_ID
WHERE UB.VIEWS = ( 
    SELECT MAX(VIEWS)
    FROM USED_GOODS_BOARD
) 
-- WHERE 절에서는 집계 함수 사용이 불가. 집계함수는 GROUP BY + HAVING 이거나 서브쿼리를 사용
-- 해당 게시글의 첨부파일만 JOIN
ORDER BY UF.FILE_ID DESC
;