SELECT 
    CH.HISTORY_ID, 
    FLOOR(
        CC.DAILY_FEE * 
        (DATEDIFF(CH.END_DATE, CH.START_DATE) + 1) * 
        (100 - COALESCE(CP.DISCOUNT_RATE, 0)) / 100
    ) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR AS CC
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH
    ON CC.CAR_ID = CH.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CP
    ON CC.CAR_TYPE = CP.CAR_TYPE
    AND CP.DURATION_TYPE =
    CASE
        WHEN DATEDIFF(CH.END_DATE, CH.START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(CH.END_DATE, CH.START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(CH.END_DATE, CH.START_DATE) + 1 >= 7  THEN '7일 이상'
        ELSE NULL
    END
WHERE CC.CAR_TYPE = '트럭'
ORDER BY FEE DESC, CH.HISTORY_ID DESC
;
